global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - 'prometheus-rules.yml'

scrape_configs:
  - job_name: 'fastapi'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['web:8000']
    scrape_interval: 5s

  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']

  - job_name: 'tempo'
    static_configs:
      - targets: ['tempo:3200']