groups:
  - name: fastapi_metrics
    rules:
      # Request rate
      - record: request_rate
        expr: rate(app_request_count_total[1m])

      # Error rate
      - record: error_rate
        expr: rate(app_error_count_total[1m])

      # Average response time
      - record: avg_response_time
        expr: rate(app_request_latency_seconds_sum[5m]) / rate(app_request_latency_seconds_count[5m])

      # Success rate
      - record: success_rate
        expr: sum(rate(app_request_count_total{status_code=~"2.*"}[5m])) / sum(rate(app_request_count_total[5m]))

      # Request duration histogram
      - record: request_duration_p95
        expr: histogram_quantile(0.95, sum(rate(app_request_latency_seconds_bucket[5m])) by (le)) 